development:
  adapter:  postgresql
  encoding: unicode
  database: sphinx_example_development
  pool:     5
  username: tiago
  password: 

test:
  adapter:  postgresql
  encoding: unicode
  database: sphinx_example_test
  pool:     5
  username: tiago
  password: 
